
dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - redis
  - docker

env:
  global:
    - LUAROCKS=2.4.3
    - OPENSSL=1.1.1a
    - CASSANDRA_BASE=2.2.12
    - CASSANDRA_LATEST=3.9
    - OPENRESTY_BASE=1.13.6.2
    - OPENRESTY_LATEST=1.13.6.2
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
    - PLUGIN_NAME=upstream-by-header
    - KONG_TEST_PLUGINS=bundled,$PLUGIN_NAME
    - KONG_PLUGINS=bundled,$PLUGIN_NAME

  matrix:
    - OPENRESTY=$OPENRESTY_BASE
      CASSANDRA=$CASSANDRA_BASE
    - OPENRESTY=$OPENRESTY_LATEST
      CASSANDRA=$CASSANDRA_LATEST

before_install:
  - git clone https://github.com/Kong/kong.git kong-ce
  - source setup_env.sh

install:
  - luarocks make
  - cd kong-ce
  - make dev
  - createuser --createdb kong
  - createdb -U kong kong_tests

script:
  - bin/busted spec/

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
